export const translateBreadcrumbEn = {
  employee: 'Employee',
  estate: 'Estate',
  teamMember: 'Team Member',
  workUnit: 'Work Unit',
  workplace: 'Work Place',
  management: 'Employee List',
  upload: 'Upload Employee',
  provider: 'Provider',
  device: 'Device',
  createEmployee: 'Create Employee',
  createDevice: 'Create Device',
  detailEmployee: 'Detail Employee',
  updateEmployee: 'Update Employee',
  detailDevice: 'Detail Device',
  updateDevice: 'Update Device',
};

export const translateBreadcrumbVi = {
  employee: 'Nhân viên',
  estate: 'Tài sản',
  teamMember: 'Thành viên',
  workUnit: 'Đơn vị công tác',
  workplace: 'Vị trí công việc',
  management: 'Danh sách nhân viên',
  upload: 'Tải lên nhân viên',
  provider: 'Nhà cung cấp',
  device: 'Tài sản',
  createEmployee: 'Thêm nhân viên',
  createDevice: 'Thêm thiết bị',
  detailEmployee: 'Chi tiết nhân viên',
  updateDevice: 'Cập nhật thiết bị',
  updateEmployee: 'Cập nhật nhân viên',
};
