export const labelDeviceVi = [
    { key: "mainActionCode", name: "Mã hành chính" },
    { key: "propertyCode", name: "Mã tài sản" },
    { key: "purchaseDate", name: "Ngày mua" },
    { key: "dateOfUse", name: "Ngày sử dung" },
    { key: "type", name: "Loại" },
    { key: "assetName", name: "Tên" },
    { key: "supplier", name: "Nhà cung cấp" },
    { key: "currentEmployee", name: "NV sử dụng hiện tại" },
    { key: "employeeUsed", name: "NV đã từng sử dụng" },
    { key: "someBills", name: "Số hóa đơn" },
    { key: "totalAmount", name: "Tổng tiền" },
    { key: "configurationDetails", name: "Chi tiết cấu hình" },
    { key: "upgradeContent", name: "Nội dung nâng cấp/sửa chữa" },
    { key: "status", name: "Tình trạng tài sản" },
    { key: "describe", name: "Mô tả" },
    { key: "dateCreated", name: "Ngày tạo" },
    { key: "updateDay", name: "Ngày cập nhật" },
  ];

export const labelDeviceEn = [
    { key: "mainActionCode", name: "Main action code" },
    { key: "propertyCode", name: "Property code" },
    { key: "purchaseDate", name: "Purchase date" },
    { key: "dateOfUse", name: "Date of use" },
    { key: "type", name: "Type" },
    { key: "assetName", name: "Name" },
    { key: "supplier", name: "supplier" },
    { key: "currentEmployee", name: "current user staff" },
    { key: "employeeUsed", name: "staff used to use" },
    { key: "someBills", name: "Some bills" },
    { key: "totalAmount", name: "Total amount" },
    { key: "configurationDetails", name: "Configuration details" },
    { key: "upgradeContent", name: "Content upgrade/repair" },
    { key: "status", name: "Property Status" },
    { key: "describe", name: "Describe" },
    { key: "dateCreated", name: "Date created" },
    { key: "updateDay", name: "Update day" },
  ];