export const labelEmployeeVi = [
    {"key": "employeeCode", "name": "Mã nhân viên" },
    {"key": "image", "name": "Ảnh" },
    {"key": "CV", "name": "CV" },
    {"key": "fullName", "name": "Họ Tên" },
    {"key": "identityCard", "name": "Số CMND/CCCD" },
    {"key": "dateRange", "name": "Ngày Cấp" },
    {"key": "isuedBy", "name": "Nơi Cấp" },
    {"key": "expirationDate", "name": "Ngày hết hạn" },
    {"key": "nation", "name": "Dân tộc" },
    {"key": "religion", "name": "Tôn giáo" },
    {"key": "nationality", "name": "Quốc tịch" },
    {"key": "educationalLevel", "name": "Trình độ văn hóa" },
    {"key": "degreeTraining", "name": "Trình độ đào tạo" },
    {"key": "trainingPlaces", "name": "Nơi đào tạo" },
    {"key": "department", "name": "Khoa" },
    {"key": "specialized", "name": "Chuyên ngành" },
    {"key": "graduationYear", "name": "Năm tốt nghiệp" },
    {"key": "classification", "name": "Xếp loại" },
    {"key": "email", "name": "Email" },
    {"key": "skypeID", "name": "SkypeID" },
    {"key": "phone", "name": "Số điện thoại" },
    {"key": "companyAccount", "name": "Tài khoản Cty" },
    {"key": "sex", "name": "Giới tính" },
    {"key": "currentPlaceOfResidence", "name": "Nơi ở hiện tại" },
    {"key": "resident", "name": "Thường trú" },
    {"key": "homeTown", "name": "Quê Quán" },
    {"key": "dateOfBirth", "name": "Ngày sinh" },
    {"key": "placeOfBirth", "name": "Nơi sinh" },
    {"key": "jobDate", "name": "Ngày nhận việc" },
    {"key": "dateOfHire", "name": "Ngày thuê" },
    {"key": "workingProcess", "name": "Quá trình tác" },
    {"key": "contractInformation", "name": "Thông tin hợp đồng" },
    {"key": "relatedProperty", "name": "Tài sản liên quan" },
    {"key": "workUnit", "name": "Đơn vị công tác" },
    {"key": "jobPosition", "name": "Vị trí công việc" },
    {"key": "describe", "name": "Mô tả" },
    {"key": "status", "name": "Trạng thái" }
  ]

export const labelEmployeeEn = [
    { key: "employeeCode", name: "Employee code" },
    { key: "image", name: "Image" },
    { key: "CV", name: "CV" },
    { key: "fullName", name: "Full name" },
    { key: "identityCard", name: "ID number" },
    { key: "dateRange", name: "Date Range" },
    { key: "isuedBy", name: "Issued by" },
    { key: "expirationDate", name: "Expiration date" },
    { key: "nation", name: "Nation" },
    { key: "religion", name: "Religion" },
    { key: "nationality", name: "Nationality" },
    { key: "educationalLevel", name: "Educational level" },
    { key: "degreeTraining", name: "Degree training" },
    { key: "trainingPlaces", name: "Training places" },
    { key: "department", name: "Department" },
    { key: "specialized", name: "Specialized" },
    { key: "graduationYear", name: "Graduation year" },
    { key: "classification", name: "Classification" },
    { key: "email", name: "Email" },
    { key: "skypeID", name: "SkypeID" },
    { key: "phone", name: "Phone" },
    { key: "companyAccount", name: "Company account" },
    { key: "sex", name: "Sex" },
    { key: "currentPlaceOfResidence", name: "Current place of residence" },
    { key: "resident", name: "Resident" },
    { key: "homeTown", name: "Home town" },
    { key: "dateOfBirth", name: "Date of birth" },
    { key: "placeOfBirth", name: "Place of birth" },
    { key: "jobDate", name: "Job date" },
    { key: "dateOfHire", name: "Date of hire" },
    { key: "workingProcess", name: "Working process" },
    { key: "contractInformation", name: "Contract information" },
    { key: "relatedProperty", name: "Related property" },
    { key: "workUnit", name: "Work unit" },
    { key: "jobPosition", name: "Job position" },
    { key: "describe", name: "Describe" },
    { key: "status", name: "Status" },
  ];