export const labelEmployeeVi = [
  { key: 'employee_code', name: 'Mã nhân viên' },
  { key: 'image_url', name: 'Ảnh' },
  { key: 'cv_url', name: 'CV' },
  { key: 'full_name', name: 'Họ Tên' },
  { key: 'identify_number', name: 'Số CMND/CCCD' },
  { key: 'dateRange', name: 'Ngày Cấp' },
  { key: 'isuedBy', name: 'Nơi Cấp' },
  { key: 'expirationDate', name: 'Ngày hết hạn' },
  { key: 'nation', name: 'Dân tộc' },
  { key: 'religion', name: 'Tôn giáo' },
  { key: 'nationality', name: 'Quốc tịch' },
  { key: 'educationalLevel', name: 'Trình độ văn hóa' },
  { key: 'degreeTraining', name: 'Trình độ đào tạo' },
  { key: 'trainingPlaces', name: 'Nơi đào tạo' },
  { key: 'department', name: 'Khoa' },
  { key: 'specialized', name: 'Chuyên ngành' },
  { key: 'graduationYear', name: 'Năm tốt nghiệp' },
  { key: 'classification', name: 'Xếp loại' },
  { key: 'email', name: 'Email' },
  { key: 'skypeID', name: 'SkypeID' },
  { key: 'mobile', name: 'Số điện thoại' },
  { key: 'companyAccount', name: 'Tài khoản Cty' },
  { key: 'gender', name: 'Giới tính' },
  { key: 'currentPlaceOfResidence', name: 'Nơi ở hiện tại' },
  { key: 'resident', name: 'Thường trú' },
  { key: 'home_land', name: 'Quê Quán' },
  { key: 'birth_date', name: 'Ngày sinh' },
  { key: 'birth_place', name: 'Nơi sinh' },
  { key: 'receive_date', name: 'Ngày nhận việc' },
  { key: 'hire_date', name: 'Ngày thuê' },
  { key: 'workingProcess', name: 'Quá trình công tác' },
  { key: 'contractInformation', name: 'Thông tin hợp đồng' },
  { key: 'relatedProperty', name: 'Tài sản liên quan' },
  {
    key: 'organization',
    name: 'Đơn vị',
    children: [{ key: 'organization_unit_name', name: 'Đơn vị công tác' }],
  },
  {
    key: 'job_position',
    name: 'Vị trí',
    children: [
      {
        key: 'job_position_name',
        name: 'Vị trí công việc',
      },
    ],
  },
  {
    key: 'employee_status',
    name: 'Trạng thái',
    children: [
      {
        key: 'employee_status_name',
        name: 'Trạng thái nhân viên',
      },
    ],
  },
  { key: 'description', name: 'Mô tả' },
];

export const labelEmployeeEn = [
  { key: 'employee_code', name: 'Employee code' },
  { key: 'image_url', name: 'Image' },
  { key: 'cv_url', name: 'CV' },
  { key: 'full_name', name: 'Full name' },
  { key: 'identify_number', name: 'ID number' },
  { key: 'dateRange', name: 'Date Range' },
  { key: 'isuedBy', name: 'Issued by' },
  { key: 'expirationDate', name: 'Expiration date' },
  { key: 'nation', name: 'Nation' },
  { key: 'religion', name: 'Religion' },
  { key: 'nationality', name: 'Nationality' },
  { key: 'educationalLevel', name: 'Educational level' },
  { key: 'degreeTraining', name: 'Degree training' },
  { key: 'trainingPlaces', name: 'Training places' },
  { key: 'department', name: 'Department' },
  { key: 'specialized', name: 'Specialized' },
  { key: 'graduationYear', name: 'Graduation year' },
  { key: 'classification', name: 'Classification' },
  { key: 'email', name: 'Email' },
  { key: 'skypeID', name: 'SkypeID' },
  { key: 'mobile', name: 'Phone' },
  { key: 'companyAccount', name: 'Company account' },
  { key: 'gender', name: 'Sex' },
  { key: 'currentPlaceOfResidence', name: 'Current place of residence' },
  { key: 'resident', name: 'Resident' },
  {
    key: 'organization',
    name: 'Unit',
    children: [
      { key: 'organization_unit_name', name: 'Organization unit name' },
    ],
  },
  {
    key: 'job_position',
    name: 'Position',
    children: [
      {
        key: 'job_position_name',
        name: 'Job position',
      },
    ],
  },
  {
    key: 'employee_status',
    name: 'Status',
    children: [
      {
        key: 'employee_status_name',
        name: 'Employee status',
      },
    ],
  },
  { key: 'home_land', name: 'Home town' },
  { key: 'birth_date', name: 'Date of birth' },
  { key: 'birth_place', name: 'Place of birth' },
  { key: 'receive_date', name: 'Job date' },
  { key: 'hire_date', name: 'Date of hire' },
  { key: 'workingProcess', name: 'Working process' },
  { key: 'contractInformation', name: 'Contract information' },
  { key: 'relatedProperty', name: 'Related property' },
  { key: 'description', name: 'description' },
];
